name: C/C++ CI

on: [push, workflow_dispatch]

concurrency: 
  group: ci-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: apt
      run: sudo apt update && sudo apt install build-essential cmake
    - name: make
      run: |
        cmake -S . -B build
        make -C build -j $(nprocs)

    - name: upload
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.event.repository.name }}.${{ github.sha }}
        path: build/telinkdebugger.uf2


